#!/usr/bin/env bash

sed -i "s|%REPLACETIMEZONE%|$PHP_Timezone|g" /etc/php8/conf.d/99-pull-journal-central.ini
su - $USERNAME -c "php /var/www/html/artisan migrate"

	if [ ! -f /var/www/html/storage/.initialseed ]; then
        su - $USERNAME -c "php /var/www/html/artisan db:seed"
        su - $USERNAME -c "touch /var/www/html/storage/.initialseed"
    fi

/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
