#!/usr/bin/env bash

[ ! -d "/var/www/html/storage/framework" ] && mkdir -p "/var/www/html/storage/framework"
[ ! -d "/var/www/html/storage/cache" ] && mkdir -p "/var/www/html/storage/cache"
[ ! -d "/var/www/html/storage/views" ] && mkdir -p "/var/www/html/storage/views"


if [[ $(stat -c "%u" /var/www/html/storage) != $UUID ]]; then
	echo "---------------"
    echo "Changing ownership of /var/www/html/storage to $UUID ..."
    chown -R $UUID:$GUID /var/www/html/storage
fi

USERNAME=$(getent passwd "$UUID")
export USERNAME=${USERNAME%%:*}
echo "---------------"
echo "detected name $USERNAME"

echo "set storage and cache permissions..."
chmod -R ug+rwx /var/www/html/storage

echo "---------------"
echo "replacing users in configs"
sed -i "s|user = .*|user = $UUID |g" /etc/php8/php-fpm.d/www.conf
sed -i "s|group = .*|group = $GUID |g" /etc/php8/php-fpm.d/www.conf
sed -i "s|%%USERNAME%%|$USERNAME|g" /etc/supervisor/conf.d/supervisord.conf
sed -i "s|%%USERNAME%%|$USERNAME|g" /etc/nginx/nginx.conf

# Database Wait check
echo "---------------"
echo "WAITING FOR $DB_HOST:$DB_PORT..."
wait-for.sh $DB_HOST:$DB_PORT --timeout=30 --strict -- start-supervisord
