#!/usr/bin/env bash

if [[ $(stat -c "%u" /var/www/html/storage) != $UUID ]]; then
	echo "---------------"
    echo "Changing ownership of /var/www/html/storage to $UUID ..."
    chown -R $UUID:$GUID /var/www/html/storage
fi

name=$(getent passwd "$UUID")
name=${name%%:*}

echo "set storage and cache permissions..."
chmod -R ug+rwx /var/www/html/storage

# Database Wait check
echo "---------------"
echo "WAITING FOR $DB_HOST:$DB_PORT..."
su - $name -c "wait-for.sh $DB_HOST:$DB_PORT --timeout=30 --strict -- start-supervisord"
